export type Options = Partial<{
  help: boolean;
  version: boolean;
  verbose: boolean;
  init: boolean | string;
  config: string;
  workdir: string;
  repository: string;
  includePath: string;
  excludePath: string;
  withCommit: string;
  skipCommit: string | string[];
  prepend: string;
  output: string;
  tag: string;
  bump: boolean;
  bumpedVersion: boolean;
  body: string;
  latest: boolean;
  current: boolean;
  unreleased: boolean;
  topoOrder: boolean;
  noExec: boolean;
  context: boolean;
  strip: "header" | "footer" | "all";
  sort: "oldest" | "newest";
  githubToken: string;
  githubRepo: string;
}>;
